### ISSUE TITLE
Polyphonic transcription

### ISSUE THREAD

**Issue by carlosholivan** [marl/crepe#63] opened 2020-08-05 16:44 UTC
I was wondering if Crepe model would allow transcriptions of instruments with polyphonic notes (for example chords played by a violin), maybe changing somehow the model and retraining it would allow it to handle polyphony?

**Comment by justinsalamon** [comment] 2020-08-07 00:59
CREPE was designed for monophonic pitch transcription. Changing the model architecture and re-training would basically amount to developing a different model. In short, CREPE is not designed for polyphonic transcription.

**Comment by fletcherist** [comment] 2020-09-14 19:36
@carlosholivan for polyphonic transcriptions i suggest you to look at [this](https://github.com/acids-ircam/timbre_exploration) project. The results and demo seems to be quite promising

**Comment by justinsalamon** [comment] 2020-09-14 19:55
@carlosholivan Another good option for polyphonic transcription is Deep Salience: https://github.com/rabitt/ismir2017-deepsalience. 

It's a couple of years old now but was state-of-the-art when released and I believe it's still pretty competitive (and easy to use).

Closing this out, cheers

**Closed by justinsalamon** 2020-09-14 19:55 UTC
